---
title: Perspectives 
format: html
---

# Perspectives on AI and Large-scale Computing

AI (artifical intelligence) or "large-scale computing" (as it is termed by [Kate Crawford](https://katecrawford.net/)) is often understood as a morally neutral technology, but this understanding obscures many of the technological insights upon which AI is built and the place of AI in a broader society. As cumulative final for this term, explore a few perspectives on AI and large-scale computing, centering on Google, the platform used in most of course instruction and a large player in the Oregon's local data center landscape.

## On the Dalles

Google's internal architecture is relatively shrouded from public knowledge, and the Dalles, Oregon is probably the site of one of Google's earliest and most important physical plants. It can be difficult to learn much about the datacenter outside of corporate press releases, and its importance was probably not fully understood by broader newsmedia during its initial rollout, but limited coverage can be found through third party internet archive services like WayBack Machine.

> Read more: [NYT Technology: Hiding in Plain Sight, Google Seeks More Power.](https://web.archive.org/web/20070312214203/https://www.nytimes.com/2006/06/14/technology/14search.html?ex=1307937600&en=d96a72b3c5f91c47&ei=5090)

As Oregon-based technologists, it is easy to adopt Google's perspective on the Dalles data center. However, many of us also have existing connections to the region, its land, and its people. For example, I moved to Oregon to be closer to relatives that work in the agriculture industry in the Columbia River Gorge, and farms in this area necessarily compete with Google's data center for resources, including land and water.

For this section, watch two features, "Google Threatens Water Supply of Drought-Stricken Town" by More Perfect Union and "Residents consider what Google data center expansion means in The Dalles" by KPTV FOX 12 Oregon. I selected two features for this section to give a perspective from a non-profit media organization and a more mainstream but corporate owned media organization. I find there is a paucity of reporting to choose from so be conscientious as you engage with this material.

### More Perfect Union

In it's own words, "More Perfect Union is a nonprofit education, advocacy, and journalism organization with a mission to build power for the working class. We tell the stories of working class Americans by covering politics, policy, labor, business, and economics news through a class lens."

> Google is racing to win approval for two massive new data centers—which use millions of gallons of water—in a small, drought-stricken farming town in Oregon. Local residents have united to fight the tech giant and preserve their water access.

> The Dalles city council unanimously voted on Monday to approve a $28.5M water deal with Google to build these two massive data centers, despite concerns from local residents and farmers. Neither Google nor the city council have revealed to residents how much water the centers will use.

*I am embedding the video below, but if the embeds do not work, here is a direct link:*

> [https://www.youtube.com/watch?v=NRTHDERxANA](https://www.youtube.com/watch?v=NRTHDERxANA)

<iframe width="100%" src="https://www.youtube.com/embed/NRTHDERxANA?si=-btVsVx6zwDS_Xyw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### KPTV FOX 12 Oregon

KPTV Fox 12 Oregon's webpage does not, to my knowledge, have a blurb attached to this feature and the webpage currently has an empty "About Us" page but is described as follows on its [Wikipedia article](https://en.wikipedia.org/wiki/KPTV):

> KPTV (channel 12) is a television station in Portland, Oregon, United States, affiliated with the Fox network. It is owned by Gray Television alongside Vancouver, Washington–licensed MyNetworkTV affiliate KPDX (channel 49).

*I am embedding the video below, but if the embeds do not work, here is a direct link:*

> [https://www.youtube.com/watch?v=peGNow7RP5M](https://www.youtube.com/watch?v=peGNow7RP5M)

<iframe width="100%" src="https://www.youtube.com/embed/peGNow7RP5M?si=1esYG-HOhW2D8aXF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## On the Wy-Kan-Ush-Pum

When considering land and water use in the US, it is especially to consider the history of land and water use prior to what the Karuk Tribe describes as "[the euro-american invasion](https://web.archive.org/web/20230208233019/https://www.karuk.us/index.php/departments/natural-resources/eco-cultural-revitalization/wildland-fire-program)" of what is now called the U.S.. 

I was unable to find any statements on Google's water usage on Grand Rhone treaty lands from the Confederated Tribes of Grand Ronde directly, but identified a feature on the Wy-Kan-Ush-Pum. According to the [Columbia River Inter-Tribale Fish Commission](https://critfc.org/salmon-culture/we-are-all-salmon-people/):

> In Sahaptin, the word for salmon used in sacred ceremonies is “wy-kan-ush.” Also in Sahaptin, the word “pum” means “people.” The tribal cultures in the Columbia River Basin could rightly be calledWy-Kan-Ush-Pum or “Salmon People” for how completely these sacred fish shaped their culture, diets, societies, and religions.

For this section, watch the following feature on the Wy-Kan-Ush-Pum from Oregon Field Guide. In it's own words, "Oregon Field Guide explores ecological issues, natural wonders and outdoor recreation. Oregon Field Guide is a valuable source of information about outdoor recreation, ecological issues, natural resources and travel destinations in Oregon and the Pacific NW."

Oregon Field Guide is a series by the the Public Broadcasting Service (PBS). In its own words, "PBS is a membership organization that, in partnership with its member stations, serves the American public with programming and services of the highest quality, using media to educate, inspire, entertain and express a diversity of perspectives. PBS empowers individuals to achieve their potential and strengthen the social, democratic, and cultural health of the U.S."

The feature is titled "Salmon People: The Fight to Preserve a Way of Life":

*I am embedding the video below, but if the embeds do not work, here is a direct link:*

> [https://player.pbs.org/viralplayer/3077392000/](https://player.pbs.org/viralplayer/3077392000/)

<div class="pbs-viral-player-wrapper" style="position: relative; padding-top: calc(56.25% + 43px);"><iframe src="https://player.pbs.org/viralplayer/3077392000/" allowfullscreen allow="encrypted-media" style="position: absolute; top: 0; width: 100%; height: 100%; border: 0;"></iframe></div>

## On Google

Perhaps the highest profile technologist to comment on Google and its use of large-scale computing is Timnit Gebru. In her own words: 

> Timnit Gebru is the founder and executive director of the Distributed Artificial Intelligence Research Institute (DAIR). Prior to that she was fired by Google in December 2020 for raising issues of discrimination in the workplace, where she was serving as co-lead of the Ethical AI research team. She received her PhD from Stanford University, and did a postdoc at Microsoft Research, New York City in the FATE (Fairness Accountability Transparency and Ethics in AI) group, where she studied algorithmic bias and the ethical implications underlying projects aiming to gain insights from data. Timnit also co-founded Black in AI, a nonprofit that works to increase the presence, inclusion, visibility and health of Black people in the field of AI, and is on the board of AddisCoder, a nonprofit dedicated to teaching algorithms and computer programming to Ethiopian highschool students, free of charge.

::: {.callout-note}

Timnit Gebru's doctoral advisor is Fei-Fei Li, who has been feature previously in this course - using specifically the term "large-scale" no less!

> [Genius 李飞飞 (Fei-Fei Li, my 🐐) said (paraphrasing) “why don’t we just label as many images as possible and see what happens”.](20_supervise.qmd#/more-data)

:::

From my own perspective as industry adjacent researcher with a doctorate in computing, Google over time has earned a reputation for hiring talent and then discplining or firing talent, [including illegally](https://www.npr.org/2021/11/29/1059821677/google-dont-be-evil-lawsuit). Timnit Gebru is perhaps the most extreme and public example of this trend. From [The Guardian](https://www.theguardian.com/lifeandstyle/2023/may/22/there-was-all-sorts-of-toxic-behaviour-timnit-gebru-on-her-sacking-by-google-ais-dangers-and-big-techs-biases):

> ... in December 2020, while she was on holiday, one of her closest colleagues texted her to ask if an email they had seen saying she had left the company was correct. Subsequent accounts said that Google had cited “behaviour that is inconsistent with the expectations of a Google manager”...

> “I was not in thinking mode. I was just in action mode, like: ‘I need a lawyer and I need to get my story out; I wonder what they’re planning; I wonder what they’re going to say about me.’” She pauses. “But I was fired. In the middle of my vacation, on a road trip to visit my mom, in the middle of a pandemic.”

Chronologically, we note that Google fired Timnit Gebru (and, in fact, the entire Ethical AI team) shortly before launching Gemini.

Google has continued its practice of illegally firing talent, with perhaps the next most high profile case related to "Project Nimbus" which has almost certainly been an enabling technology high profile war crimes in the past 12 months. There is a paywalled story from the [NYT](https://www.nytimes.com/2024/04/18/technology/google-firing-israeli-cloud-contract.html) and [Al Jazeera](https://www.aljazeera.com/economy/2024/4/19/google-fires-28-staff-after-protests-against-cloud-contract-with-israel).

For this section, watch Timnit Gebru's appearance on "Talk to Al Jazeera", an "independent new channel in the Arab world".

*I am embedding the video below, but if the embeds do not work, here is a direct link:*

> [https://www.youtube.com/watch?v=vUJVzIdRSnQ](https://www.youtube.com/watch?v=vUJVzIdRSnQ)

<iframe width="100%" src="https://www.youtube.com/embed/vUJVzIdRSnQ?si=Jj29vH0LYyIMnyY9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
